version: '3.8'

services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - processador

  processador:
    build: ./processor
    ports:
      - "8001:8001"
    depends_on:
      - armazenador

  armazenador:
    build: ./stocker
    ports:
      - "8002:8002"
